# Node.js
# Build a general Node.js project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    yarn install --frozen-lockfile
  displayName: 'yarn install'
    
- task: ShellScript@3
  inputs:
    scriptPath: $(System.DefaultWorkingDirectory)/scripts/circleci/test_entry_point.sh
    disableAutoCwd: true
    cwd: '$(System.DefaultWorkingDirectory)'
  
- script: |
    yarn test
  displayName: 'yarn test'
  
  
